FROM raspbian/stretch

# install wget, gnupg2, bc, cron and mbpoll
RUN apt update
RUN apt -y install bc cron
RUN wget -O- http://www.piduino.org/piduino-key.asc | apt-key add -
# here we have to use Raspbian sources to get Piduino armhf package
RUN echo 'deb http://raspbian.piduino.org stretch piduino' | tee /etc/apt/sources.list.d/piduino.list
RUN apt update
RUN apt -y install mbpoll

# copy files
COPY ksem_idm.sh /app/ksem_idm.sh
COPY ksem_idm_cron /etc/cron.d/ksem_idm_cron

# set workdir
WORKDIR /app

# give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/ksem_idm_cron

# apply cron job
RUN crontab /etc/cron.d/ksem_idm_cron

# run the command on container startup
CMD ["cron", "-f"]
